# Generated by Django 5.1.2 on 2025-10-26 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('address', models.TextField(verbose_name='Адрес регистрации')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('snils', models.CharField(max_length=14, unique=True, verbose_name='СНИЛС')),
                ('policy_number', models.CharField(max_length=16, verbose_name='Номер полиса ОМС')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специальность')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Номер лицензии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(verbose_name='Дата и время приема')),
                ('complaints', models.TextField(help_text='Описание текущих симптомов', verbose_name='Жалобы')),
                ('anamnesis', models.TextField(help_text='История текущего заболевания', verbose_name='Анамнез заболевания')),
                ('anamnesis_vitae', models.TextField(blank=True, help_text='Общая история здоровья', verbose_name='Анамнез жизни')),
                ('objective_status', models.TextField(help_text='Данные физикального осмотра', verbose_name='Объективный статус')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Температура (°C)')),
                ('blood_pressure', models.CharField(blank=True, help_text='Например: 120/80', max_length=10, verbose_name='АД (мм рт.ст.)')),
                ('pulse', models.IntegerField(blank=True, null=True, verbose_name='Пульс (уд/мин)')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='ЧДД (в мин)')),
                ('preliminary_diagnosis', models.CharField(max_length=200, verbose_name='Предварительный диагноз')),
                ('icd10_code', models.CharField(help_text='Например: J06.9', max_length=10, verbose_name='Код по МКБ-10')),
                ('final_diagnosis', models.CharField(blank=True, max_length=200, verbose_name='Окончательный диагноз')),
                ('examination_plan', models.TextField(help_text='Назначенные анализы и исследования', verbose_name='План обследования')),
                ('treatment_plan', models.TextField(help_text='Назначения, рекомендации', verbose_name='План лечения')),
                ('prescriptions', models.TextField(blank=True, verbose_name='Рецепты/Назначения')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации пациенту')),
                ('ai_check_performed', models.BooleanField(default=False, verbose_name='Проверка AI выполнена')),
                ('ai_check_result', models.TextField(blank=True, verbose_name='Результат проверки AI')),
                ('ai_check_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Время проверки AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='medical.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='medical.patient')),
            ],
            options={
                'verbose_name': 'Медицинская карта',
                'verbose_name_plural': 'Медицинские карты',
                'ordering': ['-visit_date'],
            },
        ),
    ]
